# Generated by Django 3.0.4 on 2020-03-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threes_made', models.IntegerField()),
                ('threes_attempted', models.IntegerField()),
                ('twos_made', models.IntegerField()),
                ('twos_attempted', models.IntegerField()),
                ('layups_made', models.IntegerField()),
                ('layups_attempted', models.IntegerField()),
            ],
        ),
    ]
